import os
from dotenv import load_dotenv

load_dotenv()

SAMPLE_RATE = 16000
FRAME_DURATION_MS = 30
SAMPLES_PER_FRAME = int(SAMPLE_RATE * FRAME_DURATION_MS / 1000)
BYTES_PER_FRAME = SAMPLES_PER_FRAME * 2
MAX_SILENCE_FRAMES = 100
RESPONSE_TIMEOUT_SECONDS = 15
SIGNING_SECRET = os.getenv("INTERVIEW_SIGNING_SECRET")
